"""empty message

Revision ID: 2654a7d4a550
Revises: 2dcd4ca70bad
Create Date: 2021-02-06 21:03:54.929532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2654a7d4a550'
down_revision = '2dcd4ca70bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faydali2', schema=None) as batch_op:
        batch_op.drop_column('title')
        batch_op.drop_column('description')

    with op.batch_alter_table('faydali3', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description3', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('title3', sa.String(), nullable=True))
        batch_op.drop_column('title')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faydali3', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('title3')
        batch_op.drop_column('description3')

    with op.batch_alter_table('faydali2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
