"""empty message

Revision ID: 2dcd4ca70bad
Revises: 621e231dc553
Create Date: 2021-02-06 17:49:43.858929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcd4ca70bad'
down_revision = '621e231dc553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faydali2', sa.Column('description2', sa.String(), nullable=True))
    op.add_column('faydali2', sa.Column('title2', sa.String(), nullable=True))
    op.drop_column('faydali2', 'description')
    op.drop_column('faydali2', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faydali2', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.add_column('faydali2', sa.Column('description', sa.VARCHAR(), nullable=True))
    op.drop_column('faydali2', 'title2')
    op.drop_column('faydali2', 'description2')
    # ### end Alembic commands ###
