"""empty message

Revision ID: 621e231dc553
Revises: 
Create Date: 2021-02-05 21:04:23.399682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621e231dc553'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faydali1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faydali2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faydali3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('faydali')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faydali',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('img', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('faydali3')
    op.drop_table('faydali2')
    op.drop_table('faydali1')
    # ### end Alembic commands ###
